 module.exports=[
    {
        city:"Boudha",
        state:"Kathmandu"
    },
    {
        city:"Lalitpur",
        state:"Kathmandu"
    },
    {
        city:"Bhaktapur",
        state:"Kathmandu"
    },
    {
        city:"Helambu",
        state:"Sinduplachok"
    },
    {
        city:"Ama Yangri",
        state:"Sinduplachok"
    },
    {
        city:"Kavre",
        state:"Lumbini"
    },
    {
        city:"Bardibas",
        state:"Jhapa"
    },
    {
        city:"Thimi",
        state:"Kathmandu"
    },
    {
        city:"Ranipoa",
        state:"Muktinath"
    },
    {
        city:"Birtamod",
        state:"Birjung"
    },
 ]